/* Autogenerated by MaKL - Thu Sep 22 18:58:58 CEST 2005 */

#ifndef _CONF_H_
#define _CONF_H_

#define OS_UNIX 1
#define HAVE_DOXYGEN 1
#define HAVE_PID_T 1
#define HAVE_GETPID 1
#define HAVE_UNLINK 1
#define HAVE_SYSLOG 1
#define HAVE_STRTOK_R 1
#define HAVE_STRERROR_R 1

#endif /* !_CONF_H_ */
