# $Id: Makefile,v 1.1 2006/11/20 13:36:12 tho Exp $

include common.mk
include ../../Makefile.conf

INCS = daemon.h fnmatch.h getpid.h gettimeofday.h strlcat.h strlcpy.h \
       strsep.h strtok_r.h syslog.h timegm.h unlink.h

INCDIR := $(INCDIR)/missing

include incs.mk
