# $Id: Makefile,v 1.2 2006/12/12 13:21:28 tho Exp $

include common.mk
include ../../Makefile.conf

INCS = daemon.h fnmatch.h getpid.h gettimeofday.h strlcat.h strlcpy.h \
       strsep.h strtok_r.h syslog.h timegm.h unlink.h mkstemps.h

INCDIR := $(INCDIR)/missing

include incs.mk
