# $Id: Makefile,v 1.2 2010/05/27 08:35:12 tho Exp $

include common.mk
include ../../Makefile.conf

PROG = blocks
SRCS = main.c 
SRCS += blocks.c 

#CFLAGS += -ggdb -DDEBUG

LDADD += $(SRCDIR)/srcs/libu.a

include prog.mk
