# $Id: Makefile,v 1.3 2007/12/14 21:06:21 tat Exp $

include common.mk
include ../../Makefile.conf

INCS = buf.h carpal.h config.h env.h hmap.h log.h logprv.h memory.h misc.h \
       net.h queue.h str.h uri.h fs.h test.h

INCDIR := $(INCDIR)/toolbox

include incs.mk
