# $Id: Makefile,v 1.2 2007/01/25 09:00:52 tat Exp $

include common.mk
include ../../Makefile.conf

INCS = buf.h carpal.h config.h env.h hmap.h log.h logprv.h memory.h misc.h \
       net.h queue.h str.h uri.h test.h

INCDIR := $(INCDIR)/toolbox

include incs.mk
