# $Id: Makefile.pkg,v 1.1 2005/10/01 17:04:51 tho Exp $

include ../../Makefile.conf

all clean depend cleandepend:

install:
	${MKINSTALLDIRS} ${DESTDIR}/doc/html && cp -r html/ ${DESTDIR}/doc/

uninstall:
	rm -rf ${DESTDIR}/doc/html

include toolchain.mk
