# $Id: Makefile.pkg,v 1.2 2005/10/01 17:10:43 tho Exp $

include ../../Makefile.conf

all clean depend cleandepend:

install:
	${MKINSTALLDIRS} ${DESTDIR}/share/html && \
		cp -r *.html *.css ${DESTDIR}/share/html/

uninstall:
	rm -rf ${DESTDIR}/share/html

include toolchain.mk
