# $Id: Makefile,v 1.1.1.1 2005/09/23 13:04:38 tho Exp $

include ../../Makefile.conf

MANFILES = libu.3 u_alloc.3 u_config.3 u_debug.3 u_env.3 u_log.3 u_misc.3 \
    u_net.3 u_str.3 u_uri.3

include man.mk
