# $Id: Makefile,v 1.2 2006/01/31 17:08:13 tho Exp $

include common.mk
include ../../Makefile.conf

MANFILES = libu.3 u_alloc.3 u_config.3 u_debug.3 u_env.3 u_log.3 u_misc.3 \
    u_net.3 u_str.3 u_uri.3

include man.mk
