# $Id: Makefile,v 1.1 2010/03/23 10:59:25 tho Exp $

include common.mk
include ../../Makefile.conf

PROG = json
SRCS = main.c json.c

#CFLAGS += -DJSON_LEX_DEBUG
#CFLAGS += -DJSON_OBJ_DEBUG

LDADD += $(SRCDIR)/srcs/libu.a

include prog.mk
