# $Id: Makefile,v 1.8 2006/01/25 11:01:46 stewy Exp $

include ../Makefile.conf

INCS = carpal.h config.h env.h hmap.h libu.h log.h logprv.h memory.h misc.h \
    net.h os.h queue.h str.h uri.h timegm.h strsep.h

include incs.mk
