# $Id: Makefile,v 1.10 2006/05/28 15:39:43 tat Exp $

include common.mk
include ../Makefile.conf

INCS = carpal.h config.h env.h hmap.h libu.h log.h logprv.h memory.h misc.h \
    net.h os.h queue.h str.h uri.h timegm.h strsep.h buf.h

include incs.mk
