# $Id: Makefile,v 1.1.1.1 2005/09/23 13:04:38 tho Exp $

include ../Makefile.conf

INCS = alloc.h config.h debug.h env.h log.h logcfg.h logprv.h misc.h net.h \
    queue.h str.h uri.h

include incs.mk
