# $Id: Makefile,v 1.1 2008/03/17 09:52:29 tho Exp $

include common.mk

PROG = pwd
SRCS = main.c

CFLAGS += -ggdb
CFLAGS += -W -Wall
CFLAGS += -I../../include
LDFLAGS += -L../../srcs -lu

include prog.mk

